/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddQuestionButton: typeof import('./src/components/AddQuestionButton.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Capabilities: typeof import('./src/components/forms/Capabilities.vue')['default']
    CapabilityDiffBadge: typeof import('./src/components/CapabilityDiffBadge.vue')['default']
    CapabilityStackedChart: typeof import('./src/components/CapabilityStackedChart.vue')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    CopyableUserPassword: typeof import('./src/components/CopyableUserPassword.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteQuestionButton: typeof import('./src/components/DeleteQuestionButton.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FormFillStatusBadge: typeof import('./src/components/FormFillStatusBadge.vue')['default']
    FormResultSummary: typeof import('./src/components/FormResultSummary.vue')['default']
    FormResultSummaryNew: typeof import('./src/components/FormResultSummaryNew.vue')['default']
    FormResultSummaryOld: typeof import('./src/components/FormResultSummaryOld.vue')['default']
    Inplace: typeof import('primevue/inplace')['default']
    InplaceSelectInput: typeof import('./src/components/forms/InplaceSelectInput.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JobFunction: typeof import('./src/components/forms/JobFunction.vue')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    OrderList: typeof import('primevue/orderlist')['default']
    Password: typeof import('primevue/password')['default']
    PhaseDisplay: typeof import('./src/components/PhaseDisplay.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    ReorderList: typeof import('./src/components/forms/ReorderList.vue')['default']
    RiskLevelBadge: typeof import('./src/components/RiskLevelBadge.vue')['default']
    RiskManagement: typeof import('./src/components/forms/RiskManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionUser: typeof import('./src/components/SessionUser.vue')['default']
    SessionUserList: typeof import('./src/components/SessionUserList.vue')['default']
    SessionUsersOrganizationChart: typeof import('./src/components/SessionUsersOrganizationChart.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Slider: typeof import('primevue/slider')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TokenStatusBadge: typeof import('./src/components/TokenStatusBadge.vue')['default']
    UserDialog: typeof import('./src/components/UserDialog.vue')['default']
    UserIcon: typeof import('./src/components/UserIcon.vue')['default']
    VulnerabilityStep: typeof import('./src/components/forms/VulnerabilityStep.vue')['default']
    XButton: typeof import('./src/components/XButton.vue')['default']
  }
}
